import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/components/providers";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

const description = "Open source product analytics on ClickHouse.";

/*
 * Social cards need absolute URLs, and a self-hosted instance has no idea what
 * its own is until someone tells it. NEXT_PUBLIC_FOURIER_HOST is already the
 * answer to that question elsewhere in the app, so reuse it rather than
 * inventing a second setting.
 */
const origin =
  process.env.NEXT_PUBLIC_FOURIER_HOST ||
  (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : "") ||
  "http://localhost:5050";

/*
 * The icons themselves are picked up from the files next to this one —
 * favicon.ico, icon.svg, apple-icon.png and opengraph-image.png. They are
 * generated by `pnpm brand`; do not edit them by hand.
 */
export const metadata: Metadata = {
  metadataBase: new URL(origin),
  title: { default: "Fourier", template: "%s · Fourier" },
  description,
  applicationName: "Fourier",
  openGraph: { title: "Fourier", description, siteName: "Fourier", type: "website" },
  twitter: { card: "summary_large_image", title: "Fourier", description },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#EEF0F2" },
    { media: "(prefers-color-scheme: dark)", color: "#141414" },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
