import type { Metadata, Viewport } from "next";
import { FourierProvider } from "@fourierhq/sdk/next";
import "./globals.css";

/*
 * The demo wears the light mark so its tab is never mistaken for the dashboard
 * next to it. favicon.ico, icon.svg and apple-icon.png sit beside this file and
 * are generated by `pnpm brand`.
 */
export const metadata: Metadata = {
  title: "Fourier demo app",
  description: "An instrumented example app, sending events to a local Fourier.",
};

export const viewport: Viewport = { themeColor: "#EEF0F2" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* This is the whole integration. Page views are tracked on every route change. */}
        <FourierProvider
          writeKey={process.env.NEXT_PUBLIC_FOURIER_WRITE_KEY ?? ""}
          host={process.env.NEXT_PUBLIC_FOURIER_HOST ?? "http://localhost:5050"}
          debug
        >
          {children}
        </FourierProvider>
      </body>
    </html>
  );
}
